language: cpp
group: travis_latest
dist: bionic

git:
  depth: 25
  quiet: true

matrix:
  include:
  - os: linux
    install:
    - mkdir build && cd build
    - cmake ..
    - cmake --build . --parallel
  - os: osx
    before_install:
    - brew install ninja
  - os: windows
    before_install:
    - cinst -y ninja

install:
- cmake -G Ninja -B build
- cmake --build build

script:
- cd $TRAVIS_BUILD_DIR/build
- ctest
